### ISSUE TITLE
Where is the module to import?

### ISSUE THREAD

**Issue by takeshi-a** [msrks/factory_automation#1]
Hi msrks,

Many thanks for your sharing of this repo with us. I'm excited to see how this repo will grow through our team development.

Here let me raise a simple question.
I could not find any import sentence in the main file, "demo.py", but there is a class called "dType" which would be defined in your scratch file or imported from dobot API. Where can I find the class definition? It is helpful for us if the definition were mentioned in the readme file. Thanks!

Best,
Takeshi

**Comment by msrks** [comment]
As you pointed out, there is no `import dType` and it is strange as a python grammar. Dobot Magician has its own IDE, and I think that `import dType` is implicitly called when running there. 

<img width="700" src="https://user-images.githubusercontent.com/9496670/37407051-1936cf48-27dc-11e8-9d32-998e6d9d1a39.png">

**Comment by takeshi-a** [comment]
Thanks. Then, I guess it is required for us to manage python executing environment properly to make the package work correctly. I will follow up the detail later.
